---
resource_types:
  - name: android-sdk-resource
    type: docker-image
    source: {repository: xaethos/android-sdk-resource}

resources:
  - name: android-sdk-linux
    type: android-sdk-resource
    source:
      components:
        - tools
        - android-23
        - build-tools-23.0.2
        - extra-android-m2repository

  - name: todo-android
    type: git
    source:
      uri: https://github.com/xaethos/todo-android.git
      branch: master

jobs:
  - name: build-debug
    plan:
      - get: android-sdk-linux
      - get: todo-android
        trigger: true
      - task: unittest
        file: todo-android/ci/test-debug-unittest.yml
      - task: assemble
        file: todo-android/ci/assemble-debug.yml
