---
resource_types:
  - name: android-sdk
    type: docker-image
    source: {repository: xaethos/android-sdk-resource}

resources:
  - name: android-sdk-linux
    type: android-sdk
    source:
      components:
        - android-23
        - build-tools-23.0.2
        - extra-android-m2repository

  - name: todo-android
    type: git
    source:
      uri: https://github.com/xaethos/todo-android.git
      branch: master

jobs:
  - name: build-debug
    plan:
      - get: android-sdk-linux
      - get: todo-android
        trigger: true
      - task: unit-test
        file: todo-android/ci/gradle-task.yml
        params:
          gradle_args: :app-singleactivity:testDebugUnitTest
      - task: assemble
        file: todo-android/ci/gradle-task.yml
        params:
          gradle_args: :app-singleactivity:assembleDebug
